CC = gcc
CFLAGS = -Wall -Wextra

all: Q1A Q1B Q1B_Bonus

Q1A: Q1A.c
	$(CC) $(CFLAGS) -o Q1A Q1A.c

Q1B: Q1B.c
	$(CC) $(CFLAGS) -o Q1B Q1B.c

Q1B_Bonus: Q1B_Bonus.c
	$(CC) $(CFLAGS) -o Q1B_Bonus Q1B_Bonus.c

clean:
	-@rm -f Q1A Q1B Q1B_Bonus
