CC = gcc
CFLAGS = -Wall -Wextra

all: Q1A Q1B Q1B_Bonus Q2A Q2B Q2C Q3

Q1A: Q1A.c
	$(CC) $(CFLAGS) -o Q1A Q1A.c

Q1B: Q1B.c
	$(CC) $(CFLAGS) -o Q1B Q1B.c

Q1B_Bonus: Q1B_Bonus.c
	$(CC) $(CFLAGS) -o Q1B_Bonus Q1B_Bonus.c

Q2A: Q2A.c
	$(CC) $(CFLAGS) -o Q2A Q2A.c

Q2B: Q2B.c
	$(CC) $(CFLAGS) -o Q2B Q2B.c

Q2C: Q2C.c
	$(CC) $(CFLAGS) -o Q2C Q2C.c

Q3: Q3.c
	$(CC) $(CFLAGS) -o Q3 Q3.c

.PHONY: clean
clean:
	rm -f Q1A Q1B Q1B_Bonus Q2A Q2B Q2C Q3
